// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  company_info: dynamic(() => import('./CompanyInfo')),
  past_projects: dynamic(() => import('./PastProjects')),
  service_owerview: dynamic(() => import('./ServiceOwerview')),
  why_us: dynamic(() => import('./WhyUs')),
}
